# Welcome to Jekyll!
#
# 
# Site settings
title: CHENZHE LUO
description: "BIOSTATISTICS，STATISTICS GENOMICS，BIOINFORMATICS"
owner: MENG LUO # or company name
#first_published: 2016 # if migrating another site, the year of your first publish
email: czheluo@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/mengluoML/mengluoCV" # the base hostname & protocol for your site
excerpt_link: "Continue reading &#8230;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"
#titlecase: true       # Converts page and post titles to titlecase
author:
  name: 'Meng Luo'
  email: czheluo@gmail.com
  github_username: mengluoML
  linkedin_username: Chenzhe Luo
  twitter_username: czheluo
  ig_username: czheluo

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-compose', 'jemoji']
social:
  twitter: https://twitter.com/czheluo
  github: https://github.com/mengluoML
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Reading Files
include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
#markdown: kramdown
#sass:
#  style: compressed

#defaults:
  # _posts
  #- scope:
     # path: ""
      #type: posts
    #values:
     # layout: single
     # author_profile: true
     # read_time: true

